version: '3.3'
services:
  frontend:
    build:
      context: client
    image: alrts-frontend
    container_name: react_app
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - backend
  backend:
    build:
      context: server
    image: alrts-backend
    container_name: express_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
